name: employee_scheduler
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.2.0
  photo_view: ^0.14.0
  file_picker: ^8.0.6
  permission_handler: ^11.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
